name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  isucon12q:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Vampire/setup-wsl@v2
        with:
          set-as-default: 'false'
      - run: Set-ExecutionPolicy RemoteSigned -Scope Process
      - name: build
        run: |
          cd isucon12-qualify
          .\build.ps1 isucon12-qualify .\isucon12-qualify
      - name: bench
        run: |
          wsl.exe ~ -d isucon12-qualify /bin/bash -c "cd bench ; ./bench -target-addr 127.0.0.1:443"
  isucon12f:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Vampire/setup-wsl@v2
        with:
          set-as-default: 'false'
      - run: Set-ExecutionPolicy RemoteSigned -Scope Process
      - name: build
        run: |
          cd isucon12-final
          .\build.ps1 isucon12-final .\isucon12-final
      - name: bench
        run: |
          wsl.exe ~ -d isucon12-final /bin/bash -c "export ISUXBENCH_TARGET=127.0.0.1 ; ./bin/benchmarker --stage=prod --request-timeout=10s --initialize-request-timeout=60s"
